spring:
  application:
    name: Spotify-Layer
  security:
    basic:
      enabled: false
    oauth2:
      client:
        clientId: ${SPOTIFY_CLIENT_ID}
        clientSecret: ${SPOTIFY_CLIENT_SECRET}
        accessTokenUri: https://accounts.spotify.com/api/token
        userAuthorizationUri: https://accounts.spotify.com/authorize
        resource:
          userInfoUri: https://api.spotify.com/v1/me